module.exports = {
  ROLES: {
    CANDIDATE: 'candidate',
    EMPLOYER: 'employer',
    ADMIN: 'admin',
  },
  APPLICATION_STATUS: {
    PENDING: 'pending',
    SHORTLISTED: 'shortlisted',
    REJECTED: 'rejected',
    ACCEPTED: 'accepted',
    WITHDRAWN: 'withdrawn',
  },
  JOB_STATUS: {
    ACTIVE: 'active',
    CLOSED: 'closed',
    DRAFT: 'draft',
  },
  JOB_TYPES: ['full-time', 'part-time', 'contract', 'internship', 'remote'],
  EXPERIENCE_LEVELS: ['entry', 'junior', 'mid', 'senior', 'lead', 'executive'],
  NOTIFICATION_TYPES: {
    APPLICATION_RECEIVED: 'application_received',
    APPLICATION_SHORTLISTED: 'application_shortlisted',
    APPLICATION_REJECTED: 'application_rejected',
    APPLICATION_ACCEPTED: 'application_accepted',
    NEW_USER_REGISTERED: 'new_user_registered',
    NEW_JOB_POSTED: 'new_job_posted',
    NEW_MESSAGE: 'new_message',
    COMPANY_VERIFIED: 'company_verified',
    INTERVIEW_SCHEDULED: 'interview_scheduled',
    INTERVIEW_RESCHEDULED: 'interview_rescheduled',
    INTERVIEW_CANCELLED: 'interview_cancelled',
    INTERVIEW_REMINDER: 'interview_reminder',
    INTERVIEW_RESULT: 'interview_result',
    INTERVIEW_INSTRUCTIONS_UPDATED: 'interview_instructions_updated',
    INTERVIEW_ACCEPTED: 'interview_accepted',
    INTERVIEW_DECLINED: 'interview_declined',
    INTERVIEW_RESCHEDULE_REQUESTED: 'interview_reschedule_requested',
    INTERVIEW_CANDIDATE_JOINED: 'interview_candidate_joined',
  },
  INTERVIEW_TYPES: [
    'online',
    'on-site',
    'phone-call',
    'technical-assessment',
    'hr-interview',
    'final-interview',
  ],
  INTERVIEW_ROUNDS: ['round-1', 'round-2', 'round-3', 'technical', 'hr', 'final'],
  INTERVIEW_STATUS: [
    'scheduled',
    'invitation_sent',
    'accepted',
    'declined',
    'reschedule_requested',
    'rescheduled',
    'reminder_sent',
    'in_progress',
    'completed',
    'cancelled',
  ],
  INTERVIEW_OUTCOME: ['pending', 'passed', 'failed', 'selected', 'rejected', 'on_hold', 'next_round'],
};
